application state added
The-Groupy-Group/job-application-tracker pull request #11
Opened 2024-11-18 17:39 UTC by tomervak

2024-11-18 18:06 UTC, IdoRoss requested changes

2024-11-18 18:06 UTC, ido-rosenberger commented on job-application-tracker-api/src/applications/applications.controller.ts
> +    async createState(@Request() request: ApiRequest,
Change route and param name according to jira ticket https://groupy-group.atlassian.net/browse/JAT-10

2024-11-18 18:06 UTC, IdoRoss commented on job-application-tracker-api/src/applications/applications.service.ts
> +        if (!application || (application.userId !== userId)) throw new NotFoundException('no such application');
Add admin check which was removed from the controller

2024-11-18 18:06 UTC, IdoRoss commented on job-application-tracker-api/src/applications/applications.service.ts
> +        const updateApplication = await this.applicationRepository.update(appId, updatedApplication);
No need to create `updatedApplication`, just send `application` to `applicationRepository.update`

2024-11-18 19:43 UTC, IdoRoss requested changes

2024-11-18 19:43 UTC, IdoRoss commented on job-application-tracker-api/src/applications/applications.controller.ts
> +        @Param('applicationId') id: string,
rename id param to applicationId

2024-11-18 19:43 UTC, IdoRoss commented on job-application-tracker-api/src/applications/applications.service.ts
> +    async update(id: string, updateApplicationDto: UpdateApplicationDto, userId: string, isAdmin: Boolean) {
use boolean istead of Boolean, Boolean is a JavaScript class

2024-11-18 19:43 UTC, IdoRoss commented on job-application-tracker-api/src/applications/applications.service.ts
> +        if (!application || !((application.userId !== userId) || isAdmin)) throw new NotFoundException('no such application');
De Morgan

2024-11-19 09:04 UTC, tomervak commented on job-application-tracker-api/src/applications/applications.controller.ts
> +    async createState(@Request() request: ApiRequest,
lo hevanti ma ata roze

2024-11-19 16:38 UTC, ido-rosenberger commented on job-application-tracker-api/src/applications/applications.controller.ts
> +            isAdmin = true;
let isAdmin: boolean = request.jwtPayLoad.roles.includes(Role.admin);

2024-11-19 16:39 UTC, ido-rosenberger approved these changes

2024-11-19 16:44 UTC, IdoRoss commented on job-application-tracker-api/src/applications/applications.service.ts
> +        return ApplicationMapper.toApplicationDto(updateApplication);
Only return the state dto

2024-11-19 16:47 UTC, ido-rosenberger commented on job-application-tracker-api/src/applications/applications.service.ts
> +    async createState(appId: string, newState: ApplicationState, userId: string) {
newState: CreateStateDto

2024-11-19 16:53 UTC, merged