ido look
The-Groupy-Group/job-application-tracker pull request #3
Opened 2024-10-17 14:44 UTC by tomervak

2024-10-20 16:39 UTC, IdoRoss requested changes

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/dto/login-user.dto.ts
> +export class loginDto{
Change to LoginRequest/LoginDto (class names always start with upper case letter)

use ctrl+r+r in your mother

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/users.controller.ts
> +    async login(@Body() loginDto:loginDto) : Promise<User>{
APIs should never return domain models. return a dto (Fix service login method comments first)

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/users.service.ts
> +    private users : User[] = [
Passwords in this array should be hashed (thought temporary)

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/users.service.ts
> +    userResponse(user :User) {
Change to "getUserResponse"
use ctrl+r+r in your mother

also add above the function decleration a comment //TODO: replace with a mapper

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/users.service.ts
> +            throw new HttpException('User not found',HttpStatus.UNPROCESSABLE_ENTITY);
Change HttpStatus to HttpStatus.NOT_FOUND (404)

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/users.service.ts
> +            throw new HttpException('Incorrect password',HttpStatus.UNPROCESSABLE_ENTITY);
Change HttpStatus to HttpStatus.BAD_REQUEST (400)

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/dto/user.dto.ts
> +export class User{
File should be under a "Models" folder as this is not a DTO but a domain model (also rename file name)

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/users.controller.ts
>  import { UsersService } from './users.service';
Reformat this file tfi wtf

2024-10-20 16:39 UTC, ido-rosenberger commented on job-application-tracker-api/src/users/users.service.ts
> +        return user;
Dont return the user, you need to create a jwt token and return it

2024-10-20 16:41 UTC, tomervak commented on job-application-tracker-api/src/users/dto/user.dto.ts
> +export class User{
this is  זמני!

2024-10-26 12:34 UTC, IdoRoss approved these changes

2024-10-26 12:34 UTC, IdoRoss commented on job-application-tracker-api/src/users/users.service.ts
> +    getUserResponse(user: User) :UserDto {
Create a file under users folder named ```user-mapper.ts```. Write a class called ```UserMapper``` and add a static function called ```toUserDto(user: User)``` and move this logic there.

2024-10-26 12:50 UTC, merged